import { REPO } from './shim.mjs';
const _store={};
globalThis.localStorage={getItem:k=>_store[k]??null,setItem:(k,v)=>{_store[k]=String(v);},removeItem:k=>{delete _store[k];}};
const se=()=>({textContent:'',innerHTML:'',value:'',onclick:null,style:{},classList:{add(){},remove(){},toggle(){},contains(){return false;}},appendChild(){},removeChild(){},querySelector(){return null;},querySelectorAll(){return[];},setAttribute(){},getAttribute(){return null;},addEventListener(){},remove(){}});
globalThis.document={getElementById:()=>se(),createElement:()=>se(),querySelector:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},body:se()};
globalThis.window={};
const S=await import(REPO+'/season.js'),ST=await import(REPO+'/state.js');
const {G,SetupState}=ST;
S.registerSeasonCallbacks({addLog(){},updateAll(){},navTo(){},startConfTourney(){},playTournamentGame(){},openModal(){}});
S.buildUniverse(); G.tid=0; ST.resetLS(); S.buildSchedules();
const pool=G.teams.filter(x=>x.id!==0&&x.conf!==G.teams[0].conf);
SetupState.NC_PICKS=pool.slice(0,10).map(x=>x.id);
S.setupUserOOC();
const slot=0, oldOpp=G.teams[0].sched[slot].opp;
console.log('slot0 old opp:', G.teams[oldOpp].name, '| old opp mirror:', JSON.stringify(G.teams[oldOpp].sched[slot]&&{opp:G.teams[oldOpp].sched[slot].opp}));
S.swapOOC(slot, 5);
const newOpp=5;
console.log('after swapOOC(0,5): user slot0 opp =', G.teams[0].sched[slot].opp);
console.log('old opp(',G.teams[oldOpp].name,') sched[0].opp =', G.teams[oldOpp].sched[slot]&&G.teams[oldOpp].sched[slot].opp, '(still points at user=0 => dangling game)');
console.log('new opp(',G.teams[newOpp].name,') sched[0].opp =', G.teams[newOpp].sched[slot]&&G.teams[newOpp].sched[slot].opp, '(should be 0 if mutual)');
process.exit(0);
